# Usar a imagem oficial do Node.js como base
FROM node:18

# Diretório de trabalho dentro do container
WORKDIR /app

# Copiar package.json e package-lock.json (se existir) para o container
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar o restante dos arquivos do projeto para o diretório de trabalho correto dentro do container
COPY . .

# Expor a porta que o servidor irá rodar
EXPOSE 8080

# Comando para rodar o servidor
CMD ["node", "src/server.js"]
